# Generated by Django 4.2 on 2025-07-12 12:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DossierAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('STATUS_CHANGE', 'Changement de statut'), ('ATTACHMENT_ADD', 'Ajout de pièce jointe'), ('ATTACHMENT_REMOVE', 'Suppression de pièce jointe'), ('CONTROLLER_ASSIGN', 'Assignation de contrôleur')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Dossier Audit Log',
                'verbose_name_plural': 'Dossier Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('UNDER_REVIEW', 'En révision'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('doctor', models.CharField(max_length=100)),
                ('diagnosis', models.TextField()),
                ('treatment_plan', models.TextField()),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('is_confidential', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Dossier Médical',
                'verbose_name_plural': 'Dossiers Médicaux',
                'ordering': ['-priority', '-created_at'],
                'permissions': [('can_review', 'Can review medical dossiers'), ('can_approve', 'Can approve medical dossiers'), ('view_confidential', 'Can view confidential dossiers')],
            },
        ),
        migrations.CreateModel(
            name='MedicalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_attachments/%Y/%m/%d/')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('PRESCRIPTION', 'Ordonnance'), ('CERTIFICATE', 'Certificat médical'), ('SCAN', 'Radiographie/Scanner'), ('TEST', 'Résultat de test'), ('REPORT', 'Rapport médical'), ('OTHER', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('size_kb', models.IntegerField(editable=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dossier_medicale.dossiermedical')),
            ],
            options={
                'verbose_name': 'Medical Attachment',
                'verbose_name_plural': 'Medical Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
