# Generated by Django 4.2 on 2025-07-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('dossier_medicale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='controller',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['CONTROLLER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_dossiers', to='user.user'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s', to='user.user'),
        ),
        migrations.AddField(
            model_name='dossierauditlog',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='dossier_medicale.dossiermedical'),
        ),
        migrations.AddField(
            model_name='dossierauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
    ]
