# Generated by Django 4.2 on 2025-07-12 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_medicale', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('chemin_storage', models.FileField(upload_to='pieces_jointes/')),
                ('type', models.CharField(max_length=50)),
                ('taille_ko', models.IntegerField()),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dossier_medicale.dossiermedical')),
            ],
        ),
    ]
