# Generated by Django 4.2 on 2025-07-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_medicale', '0003_piecejointe'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
