# Generated by Django 4.2 on 2025-07-15 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dossier_medicale', '0004_dossiermedical_comments_dossiermedical_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecejointe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='piecejointe',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_pieces', to=settings.AUTH_USER_MODEL),
        ),
    ]
