# Generated by Django 4.2 on 2025-07-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_medicale', '0005_piecejointe_description_piecejointe_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecejointe',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='dossier_medicale.dossiermedical'),
        ),
    ]
