# Generated by Django 4.2 on 2025-07-15 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dossier_medicale', '0006_alter_piecejointe_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='employer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['AGENT', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_dossiers', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Employer'),
        ),
    ]
