# Generated by Django 4.2 on 2025-07-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_medicale', '0008_remove_dossiermedical_employee_id_and_more'),
    ]

    operations = [
    ]
