# Generated by Django 4.2 on 2025-07-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_medicale', '0009_remove_employee_id'),
        ('dossier_medicale', '0010_fix_employee_id_removal'),
    ]

    operations = [
    ]
