# Generated by Django 4.2.27 on 2026-01-18 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dossier_medicale', '0011_merge_20250715_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='managed_dossiers', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Employer'),
            preserve_default=False,
        ),
    ]
