# Generated by Django 6.0.1 on 2026-01-19 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_medicale', '0012_alter_dossiermedical_employer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriseEnCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('UNDER_REVIEW', 'En révision'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=200, verbose_name='Établissement')),
                ('care_type', models.CharField(choices=[('INPATIENT', 'Hospitalisation'), ('OUTPATIENT', 'Ambulatoire'), ('MATERNITY', 'Maternité'), ('PHARMACY', 'Pharmacie'), ('OTHER', 'Autre')], max_length=20, verbose_name='Type de soin')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Coût estimé')),
                ('coverage_percentage', models.IntegerField(default=100, verbose_name='Taux de couverture')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('diagnosis', models.TextField(verbose_name='Diagnostic')),
                ('physician', models.CharField(max_length=100, verbose_name='Médecin traitant')),
                ('comments', models.TextField(blank=True, verbose_name='Commentaires')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_coverages', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Prise en Charge',
                'verbose_name_plural': 'Prises en Charge',
                'ordering': ['-created_at'],
            },
        ),
    ]
