# Generated by Django 6.0.1 on 2026-01-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_medicale', '0013_priseencharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'Médecine Générale'), ('OPTIQUE', 'Optique'), ('CARDIOLOGIE', 'Cardiologie'), ('DENTAIRE', 'Dentaire'), ('ORL', 'ORL'), ('DERMATOLOGIE', 'Dermatologie'), ('AUTRE', 'Autre')], default='GENERAL', max_length=50, verbose_name='Catégorie de dossier'),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
