# Generated by Django 6.0.1 on 2026-01-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_medicale', '0014_dossiermedical_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priseencharge',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Département'),
        ),
    ]
