# Generated by Django 6.0.1 on 2026-01-19 17:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier_medicale', '0015_priseencharge_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='priseencharge',
            name='care_type',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('HOSPITALIZATION', 'Hospitalisation'), ('PHARMACY', 'Pharmacie'), ('LABORATORY', 'Laboratoire / Examens'), ('SURGERY', 'Chirurgie'), ('DENTAL', 'Soins Dentaires'), ('OPTICAL', 'Optique'), ('OTHER', 'Autre')], default='CONSULTATION', max_length=50, verbose_name='Type de soin'),
        ),
        migrations.AlterField(
            model_name='priseencharge',
            name='coverage_percentage',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de couverture'),
        ),
        migrations.AlterField(
            model_name='priseencharge',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coût estimé'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priseencharge',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pec_requests', to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='priseencharge',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de début'),
        ),
    ]
