# Generated by Django 4.2 on 2025-07-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_role_permissions_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the employee in the organization', max_length=50, null=True, unique=True, verbose_name='employee ID'),
        ),
    ]
