# Generated by Django 4.2 on 2025-07-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
    ]
