# Generated by Django 4.2.27 on 2026-01-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the employee in the organization', max_length=50, null=True, unique=True, verbose_name='employee ID'),
        ),
    ]
