# Generated by Django 6.0.1 on 2026-01-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Department the user belongs to', max_length=100, null=True, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('AGENT', 'Medical Agent'), ('CONTROLLER', 'Quality Controller'), ('ADMIN', 'System Admin')], max_length=20, unique=True),
        ),
    ]
